name: picker_view
description: A Flutter picker view like iOS UIPickerView support multiple pickers.
version: 1.0.1
homepage: https://github.com/sososdk/picker_view.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
